#!/usr/bin/env bash
# weekly.sh — generate Telegram-ready digest + memory log entry.
#
# Usage:
#   weekly.sh                  # full digest for both bootcamps
#   weekly.sh mw01             # one bootcamp only
#   weekly.sh --send           # also send via Telegram (uses notify.sh)
#   weekly.sh --memory         # also append to memory/YYYY-MM-DD.md
#   weekly.sh --send --memory  # both

set -uo pipefail

SKILL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
AIRI_SKILL_DIR="/app/data-intelligence-architect/skills/airi-model-switcher"
MEMORY_DIR="/app/data-intelligence-architect/memory"
TODAY="$(date -u '+%Y-%m-%d')"
MEMORY_FILE="${MEMORY_DIR}/${TODAY}.md"

bootcamp_filter="${1:-}"
do_send=0
do_memory=0
for arg in "$@"; do
  case "$arg" in
    --send) do_send=1 ;;
    --memory) do_memory=1 ;;
  esac
done

mkdir -p "$MEMORY_DIR"

echo "📊 **Bootcamp Weekly Digest** — ${TODAY}"
echo "═══════════════════════════════════════"
echo ""

if [[ -z "$bootcamp_filter" || "$bootcamp_filter" == "mw01" ]]; then
  python3 "${SKILL_DIR}/scripts/status.py" mw01
fi

if [[ -z "$bootcamp_filter" || "$bootcamp_filter" == "msc-ire" ]]; then
  python3 "${SKILL_DIR}/scripts/status.py" msc-ire
fi

echo ""
echo "═══════════════════════════════════════"
echo "Generated by skills/bootcamp-orchestrator"

# Memory log
if [[ $do_memory -eq 1 ]]; then
  {
    echo ""
    echo "## 📊 Bootcamp digest — ${TODAY}"
    echo ""
    if [[ -z "$bootcamp_filter" || "$bootcamp_filter" == "mw01" ]]; then
      python3 "${SKILL_DIR}/scripts/status.py" mw01 | sed 's/^/  /'
    fi
    echo ""
    if [[ -z "$bootcamp_filter" || "$bootcamp_filter" == "msc-ire" ]]; then
      python3 "${SKILL_DIR}/scripts/status.py" msc-ire | sed 's/^/  /'
    fi
  } >> "$MEMORY_FILE"
  echo ""
  echo "✓ Logged to $MEMORY_FILE"
fi

# Telegram
if [[ $do_send -eq 1 ]]; then
  MSG=$(python3 "${SKILL_DIR}/scripts/status.py" $bootcamp_filter --all 2>/dev/null || cat)
  if [[ -x "${AIRI_SKILL_DIR}/scripts/notify.sh" ]]; then
    "${AIRI_SKILL_DIR}/scripts/notify.sh" "$MSG" 2>&1 | sed 's/^/  /'
  else
    echo "(notify.sh not found at ${AIRI_SKILL_DIR}/scripts/notify.sh — skipping telegram)"
  fi
fi